#kubectl patch deployment reverse-proxy -n k8s-tutorial --patch-file k8s/10-rp_patch.yaml
spec:
  template:
    spec:
      containers:
      - name: reverse-proxy
        volumeMounts:
        - name: certs-volume
          mountPath: "/etc/certs"
          readOnly: true
      volumes:
      - name: certs-volume
        projected:
          sources:
          - secret:
              name: reverse-proxy-mtls-tls
          - configMap:
              name: internal-trust-bundle