# v1
# cat <<EOF | kubectl apply -f -
# apiVersion: trust.cert-manager.io/v1alpha1
# kind: Bundle
# metadata:
#   name: internal-trust-bundle
# spec:
#   sources:
#   - secret:
#       name: "root-ca-secret"
#       key: "ca.crt"
#   target:
#     configMap:
#       key: "internal-ca.crt"

#v2
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: ca-bundle
spec:
  sources:
  - secret:
      name: "root-ca-secret"
      key: "ca.crt"
  target:
    configMap:
      key: "root-ca.crt"