# v1
# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#   name: selfsigned-issuer
#   namespace: cert-manager # We'll keep it here for now
# spec:
#   selfSigned: {}

# v2
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: root-ca-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  namespace: cert-manager
spec:
  isCA: true   # This is the "Stamp" we talked about earlier
  commonName: "my-internal-ca"
  secretName: root-ca-secret
  issuerRef:
    name: root-ca-issuer
    kind: Issuer